<script type="text/javascript" src="<?php echo EXT_PATH ?>js/index.js"></script>
<script type="text/javascript" src="<?php echo EXT_PATH ?>js/usuario/index.js"></script>
			<div id="home">
				<p class="caminho"></p>
					<form method="post" action="#" class="form" id="form_salvar" name="form_salvar">
						<table class="nav2" id="tit" style="margin-bottom:10px;">
							<thead>
								<tr class="nav3">
									<th colspan="8">
										<a href="javascript:acao('/usuario/new')"><img class="iconNav" src="<?php echo EXT_PATH; ?>images/icon_novo.png" width="14" height="14" alt="" id="NovoUser" />Novo</a>
										<a id="edit" href="javascript:selecionar('usu&aacute;rio')"><img class="iconNav" src="<?php echo EXT_PATH; ?>images/icon_editar.png" width="15" height="14" alt="" id="linkEditar" />Editar</a>
										<a id="excluir" href="javascript:selecionar('usu&aacute;rio')"><img class="iconNav" src="<?php echo EXT_PATH; ?>images/icon_excluir.png" width="14" height="14" alt="" />Excluir</a>
										<a id="ver" href="javascript:selecionar('usu&aacute;rio')"><img class="iconNav" src="<?php echo EXT_PATH; ?>images/search_lense.png" width="14" height="14" alt="" />Visualizar</a>
										<span class="tit_table">LISTAGEM USU&Aacute;RIOS</span>
									</th>
								</tr>
							</thead>
						</table>
						<table id="example">
							<thead>
								<tr class="nav1">
									<th></th>
									<th>Nome</th>
									<th>Usu&aacute;rio</th>
									<th>E-mail</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($this->usuarios as $usuario) : ?>
								<tr>
									<td><input type="radio" name="id_usuario" id="id_usuario" value="<?php echo $usuario['id_usuario']; ?>" /></td>
									<td><?php echo $usuario['no_usuario']; ?></td>
									<td><?php echo $usuario['no_login']; ?></td>
									<td><?php echo $usuario['no_email']; ?></td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</form>
			</div><!-- fecha home content-->