<script type="text/javascript" src="<?php echo EXT_PATH ?>js/usuario/new.js"></script>

<div id="editar">
				<p class="caminho"></p>
				<ul class="tabs">
					<li><a>Usu&aacute;rio</a></li>
				</ul>
				<div id="tab1">
					<form method="post" action="#" class="form" id="form_salvar" name="form_salvar">
						<div class="container_col">
						<div class="col3">
							<p class="tit_form">Dados</p>
							<div class="row">
								<label for="nome"><span class="obrigatorio">*</span> Nome completo:</label>
								<input type="text" name="no_usuario" value="" size="33" class="required" minLength="6" maxLength="100"/>
							</div> <!-- fecha row -->

							<div class="row">
								<label for="login"><span class="obrigatorio">*</span> Login:</label>
								<input type="text" name="no_login" value="" size="20" />
							</div> <!-- fecha row -->

							<div class="row">
								<label for="email"><span class="obrigatorio">*</span> E-mail:</label>
								<input type="text" name="no_email" value="" size="33" />
							</div> <!-- fecha row -->

							<div class="row">
								<label for="senha"><span class="obrigatorio">*</span> Senha:</label>
								<input type="password" name="no_senha" value="" class="required" id="senha" minLength="6" maxlength="8" size="20" /> 
							</div> <!-- fecha row -->

							<div class="row">
								<label for="confsenha"><span class="obrigatorio">*</span> Confirmar Senha:</label>
								<input type="password" name="no_csenha" value="" class="required" equalTo="#senha" minLength="6" maxlength="8" size="20" /> 
							</div> <!-- fecha row -->
						</div><!-- fecha col-->
						<div class="col3">
						</div>
						
						</div>
						<div  class="clearfix"> </div>
						<p class="obrigatorio"><span class="obrigatorio">(*)</span> Campo(s) obrigat&oacute;rio(s)</p>
						<div class="btn">
							<div id="errorDiv1" class="error-div"></div>
							<a href="javascript:acao('/usuario')" class="uibutton" id="btnCancelar">Cancelar</a>
							<input type="submit" id="submit" value="Salvar" class="uibutton" id="btnSalvar"/>
						</div><!-- fecha btn-->
						
					</form>
				</div><!-- fecha tab1 -->

			</div><!-- fecha listagemClientes -->