<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/reset.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/design.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/tab.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/fb-buttons.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/colorbox.css" type="text/css" media="screen" /> <!-- para a janela modal -->
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/redmond/jquery-ui-1.8.21.custom.css" type="text/css" media="screen" /> <!-- para o date picker-->
	<!--[if ie]> 
	<link rel="stylesheet" href="<?php echo EXT_PATH; ?>css/ie.css" type="text/css" media="screen" />
	 <![endif]-->
	<script type="text/javascript" src="<?php echo EXT_PATH; ?>js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo EXT_PATH; ?>js/jquery-ui-1.8.21.custom.min.js"></script> <!-- para o date picker-->
	<script type="text/javascript" src="<?php echo EXT_PATH; ?>js/jquery.corner.js"></script><!-- para os cantos arredondados -->
	<script type="text/javascript" src="<?php echo EXT_PATH; ?>js/jquery.colorbox.js"></script> <!-- para a janela modal-->
	<script type="text/javascript" src="<?php echo EXT_PATH; ?>js/jquery.dataTables.js"></script>
	<script type="text/javascript" src="<?php echo EXT_PATH ?>js/jquery.validate.js"></script>
	<script type="text/javascript" src="<?php echo EXT_PATH ?>js/jquery.maskedinput-1.2.2.min.js"></script>
	<script type="text/javascript" src="<?php echo EXT_PATH ?>js/jquery.editable-set.js"></script>
	<script type="text/javascript" src="<?php echo EXT_PATH ?>js/layout.js"></script>
	<title>Sistema de Controle Imobili&aacute;rio</title>
	
</head>
<body id="controlaEventos">
	<div id="boxes" class="container clearfix">
	<div id="modal" class="window"></div>
	<div id="mask"></div>
	
		<div id="topo" class="clearfix">
			<h1>Sistema de Controle Imobili&aacute;rio</h1>
			<div id="mensagem" class="mensagem"></div>
			<img src="<?php echo EXT_PATH; ?>images/icon_logout.png" width="16" height="16" alt="Logout" id="logout" class="iconLogout" />
			<p><a class="logout" href="<?php echo $this->baseUrl ?>/auth/logout">Usu&aacute;rio: <?php echo $this->escape($this->user->no_usuario); ?></a></p>
		</div><!-- fecha topo-->

		<div id="header"> 
			<div id="menu">
				<h3 class="trigger"><a>Aluguel</a></h3>
				<div class="toggle_container" style="display: none;">
					<div class="block">
						<p><a href="javascript:acao('/locador')">Locador</a></p>
						<p><a href="javascript:acao('/locatario')">Locat&oacute;rio</a></p>
						<p><a href="javascript:acao('/imovel/index/tipo/1')">Im&oacute;veis</a></p>
					</div><!-- fecha block -->
				</div> <!-- fecha toggle_container -->
				
				<h3 class="trigger"><a href="#">Venda</a></h3>
				<div class="toggle_container" style="display: none;">
					<div class="block">
						<p><a href="javascript:acao('/vendedor')">Vendedor</a></p>
						<p><a href="javascript:acao('/comprador')">Comprador</a></p>
						<p><a href="javascript:acao('/imovel/index/tipo/2')">Im&oacute;veis</a></p>
					</div><!-- fecha block -->
				</div> <!-- fecha toggle_container -->

				<h3 class="trigger"><a href="#">Contratos</a></h3>
				<div class="toggle_container" style="display: none;">
					<div class="block">
						<p><a href="#">Imobili&aacute;ria</a></p>
						<p><a href="#">Venda</a></p>
						<p><a href="#">Aluguel</a></p>
					</div><!-- fecha block -->
				</div> <!-- fecha toggle_container -->

				<h3 class="trigger"><a href="#">Relat&oacute;rios</a></h3>
				<div class="toggle_container" style="display: none;">
					<div class="block">
						<p><a href="#">Listagem Clientes</a></p>
						<p><a href="#">Tipo 2</a></p>
					</div><!-- fecha block -->
				</div> <!-- fecha toggle_container -->

				<h3 class="trigger"><a>Seguran&ccedil;a</a></h3>
				<div class="toggle_container" style="display: none;">
					<div class="block">
						<p><a href="javascript:acao('/usuario')">Usu&aacute;rio</a></p>
						<p><a href="javascript:acao('/usuario/trocasenha')">Troca Senha</a></p>
						<p><a href="javascript:acao('/auditoria')">Auditoria</a></p>
					</div><!-- fecha block -->
				</div> <!-- fecha toggle_container -->
			</div><!-- fecha menu-->

			<div id="alertas">
				<p class="tit_alertas">alertas</p>
				<p>Boletos vencidos<span class="alertas" id="alerta1">10</span></p>
				<p>Boletos a vencer<span class="alertas" id="alerta2">4</span></p>
				<p>Contratos a vencer<span class="alertas" id="alerta3">3</span></p>
			</div><!-- fecha alertas-->

		</div><!-- fecha header-->
		
		<div id="loading" class="load"><img src="<?php echo EXT_PATH; ?>images/carregando6.gif" /></div>
		<div id="conteudo" class="clearfix">
		
			<?php echo $this->layout()->content; ?>
			
		</div> <!--fecha conteudo-->
      </div><!-- fecha container -->
</body>
</html>